id: P74079B2D
initial_creation_type: ocr
source_metadata:
  volumes:
    e3ec253065694aac870a5619c2749531:
      base_file: v075.txt
      image_group_id: I1PD95920
      title: རྣམ་གྲངས་བསྡུ་བ།
      total_pages: 1529
      volume_number: 75
